name: Deploy DAGs to Composer
# on:
#   push:
#     branches:
#       - main
on: [push]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: root-409@pristine-cairn-318322.iam.gserviceaccount.com #${{ secrets.GCP_EMAIL }}
        service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicHJpc3RpbmUtY2Fpcm4tMzE4MzIyIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMzdhMjM3Mzc3NWZkZWFkZmVlOWYyYTNiYzdmZWM2MDdhZGM1ZWM3ZCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDVXFqNFBjN2x0NE10Q1xuZ0lDa3NXUlNmT1ltZjA5MTBleDBNZWoxSUQvem12cXM0K1R2NlBQR3B1NVFENHUxRDVzaFNBYVZ3Y3hVOWE2VlxuWlFHaXNCbVBmNnhPbmFpNHQ3eVNrcWRLOEw0ZlBPUkd2TURhenE0QWZZUjlGQWw0ZmtmYXlPNmtnZUhHMTJTdFxuNFVwWTdFVExSeEZJMVZIK2JvRWZRaVFwcW82bkRWdGI3MUhLd3NjRTVMV1FKVDJueVViTTh1cmhmUEtHKzFNalxuMWl3U3NPTlNPU0NTL05IRWcvMHhoUHh4QTRaRm1nRmVNbkpzVkJySXdlMlY5bTNhTzlEcHpJTExtWmRyU0dkc1xuSDJ0U1pXQnc3UzBTdm1YY0VKSXp1VHVLTEFjV25ISENMLzVCYmUrYVVBUGZ3WldIcTdFbUFUa2NXWlpERkdQM1xuc0MyM01RZmxBZ01CQUFFQ2dnRUFFT284NVBPeEc3b3B6bCtDSTVzR2MrYy9wWTR6TzQvZTFFcXdlNkdIZlQ5N1xuT2F3MWFvR3FLUVpwMDZTdEsvVUNYTnROMm9EQ0w4R0RjMzZhWE1rbUkyQnV1Y1F4QkJGdHpJeVFxZE55QW1waVxuZTlUeXFZSytKQktqL2pwSEtKVlB0aXBLRXVBdlVQbEZmSTVIY0E0ejlxQVhySjZPOVlEYndyTjdHMTJMWFNEWVxudzg2THlycVFuT3o3NGM5c243VDEwUVZ6eTB1d29qbnlIanBEclhrYkNMbkRRdE1uMVVtSWhyL2tHcTcvOGFXUFxuN2ZWVk9OaTlvbXF4dS9UUVRyd01PbXlVQkpoOWlWbWR0dzVVNUowSTJwQTZDSnptcWZvUEluMWZFM0N4VzlvbVxuWSs5SnRLUVRDdStxU0ZBKytxamNsS3pVS1FKYnlLaFRYQ3lkaHRjOFdRS0JnUURKS0tYbStvRkdYYlY0ZjNmc1xuWGU3cDBrUzlIeTlFTTd4MGF1d3k1U25oRm1FWXNGd0d3Z1Vnak51SDdEMW1yTXd2Yk1XMW04TFFrRXFaK0VGbFxuNEMrRUpaUmZpVjRVcjdCellKV1pJZXdWbzF5c21MNURyVHF6MmdDbXl5aG1HUjVlMFU2RzhvanRJeXFEMmlPaVxucDM4Q29uOW9wWDJGZG0zc00vNjZyQ2JqMlFLQmdRQzlNZTI1TjM2NnN2VHpXSUU0b2xTWldmbVJiRUNubHkwS1xuVE1xaDBuOHNINjZYNXZDRnBUSTdjcS9jNnVmdmRaalY3dkdpN210OTVxU3d0WFJGODZJUUdxRVhMVDBUcU1pSlxuMkFYTERPSWZ2VlRoMkgyNW9aSlRrclBEaWFEYkl5ZFQzZnZhZWdOL2hGQmhoeU96dWZwVG1tYU5aU0tzMFVmK1xuL0tRZEJOblk3UUtCZ0NyN0QyK3A2TU5UTkhvWnFsTUx3d2VjME9rajU2S0g5MlZjanpsVXM3MFBYaEc3WlA1Z1xucUYzTEd3RVEzaEc1TEN1Wjd5aWRybU9INFJqQzdaNUo1MzB4MW1FUFpkVy9zRkVHdXhBc0tsaDVQa3oybWZpMVxuNDh3WDhYbXlBT0RIenpCdFFuMGRCMXE3MzlLcVltRFhyeEN1RGRFYlF4V29OMVozeVo2ek4rQUpBb0dBZnJjUVxuRnp0Wi84V1lWZHZ6UUhGSTVDVGxDRWRPem5Cc1ZEZTJoOGVxTVcxT3pLSjZlYWg1Q21QMzhhakxpeEJpT3ZiOFxubERuSGVOMmZkRk16K3g0QWIzVEdhL1Y2c000YzhtWGpDMm9ua1VhSHNYUUVVTzRzU1JrNm1UNTJwQTdaYWt5RlxuUUlEMEV0WVYyQnhoQnlFS3ppL2RlOW8rN1N5R1lmdm9GeCtHb01rQ2dZRUFsck1waDVDcERNSTQ1YlpCUWZ4RFxuYWM0clNQSjF4d1NlbWlIM0lkSTVrNlhKaC9KRXFBa1FyY056NTlmVEFxNkJSZG5JTHgxRmFVUTgrNEdFT29RRlxuRDFEUDNZZ3h0bFJlNnFBcGMyQm55dzhzeTFPZnRTYVB3cGsxWitmRVBmRUhkVUhIbnNsT3VwbkpCeFRGQk02SFxuTVUyaHZmZFl1dHptVVBYU2Nnc2JhWTg9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAicm9vdC00MDlAcHJpc3RpbmUtY2Fpcm4tMzE4MzIyLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwODM3ODkwNTc4MTkwNzQ3MDkxMCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvcm9vdC00MDklNDBwcmlzdGluZS1jYWlybi0zMTgzMjIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K #${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
        project_id: pristine-cairn-318322 #${{ secrets.GCP_PROJECT_ID }}

    - name: Use gcloud CLI
      run: gcloud info

    # Upload files to GCS
    - id: upload-file
      name: upload DAGs to GCS
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./dags/tutorial.py
        destination: europe-west1-firstcomposer-de8e6ba3-bucket/dags/

    # Example of using the output
    - id: uploaded-files
      name: output the file name uploaded
      uses: google-github-actions/upload-cloud-storage@main
      env:
        file: ${{steps.upload-file.outputs.uploaded}}%