name: Test DAGs

on: [push]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key:  ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Use gcloud CLI
      run: gcloud info

    - id: upload-dags-to-data-dir
      name: upload DAGs to GCS data dir for test
      run: |
        gsutil cp ./dags/** gs://europe-west1-firstcomposer-de8e6ba3-bucket/data/test/
    
    # Run the test on the GCS folder that  has the DAGs
    - id: test-dags
      name: test dags
      run: |
        gcloud composer environments run firstcomposer --location europe-west1 --project pristine-cairn-318322  list_dags -- -sd /home/airflow/gcs/data/test | sed -e '1,/DAGS/d' | tail -n +2
        gcloud composer environments run firstcomposer --location europe-west1 --project ${{ secrets.GCP_PROJECT_ID }}  list_dags -- -sd /home/airflow/gcs/data/test 
        if [[ $? == 1 ]]; then 
          echo -e "the tests failed. Issue with some DAGs" 
        else 
          echo "DAGs passed tests" 
        fi